# fly.toml file generated for ancient-thunder-1127 on 2023-03-25T04:09:15-05:00

app = "ancient-thunder-1127"
kill_signal = "SIGTERM"
kill_timeout = 5
mounts = []
primary_region = "bog"
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "ancient-thunder-1127.fly.dev"
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
